# @package _global_

defaults:
  - override /hydra/launcher: submitit_local

hydra:
  launcher:
    timeout_min: 10_080   # 7 days
    nodes: 1
    tasks_per_node: ${trainer.devices}
    cpus_per_task: 6
    gpus_per_node: ${trainer.devices}
    name: hmr2
