# main image
FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04

RUN printf "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy main restricted universe multiverse\ndeb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy main restricted universe multiverse\ndeb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse\ndeb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse\ndeb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse\ndeb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse\ndeb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse\ndeb-src http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse" > /etc/apt/sources.list

RUN apt update && apt install -y wget gcc g++ meson llvm libgl1-mesa-glx libosmesa6 libosmesa6-dev python3 python3-pip ffmpeg libsm6 libxext6

RUN apt-get build-dep -y mesa

RUN apt-get clean && rm -rf /var/lib/apt/lists/


# build mesa3d as offscreen rendering backend of pyrender
RUN pip install mako

RUN cd / && wget https://archive.mesa3d.org/mesa-22.3.7.tar.xz && tar -xvf mesa-22.3.7.tar.xz && \
    cd /mesa-22.3.7 && meson setup builddir/ && meson compile -C builddir/ && meson install -C builddir/ && \
    cd / && rm -rf mesa-*

ENV PYOPENGL_PLATFORM osmesa

# download blender
RUN cd / && wget https://download.blender.org/release/Blender3.6/blender-3.6.11-linux-x64.tar.xz && tar -xvf /blender-3.6.11-linux-x64.tar.xz && mv /blender-3.6.11-linux-x64 /blender && ln -s /blender/blender /usr/bin/blender

RUN /blender/3.6/python/bin/python3.10 -m pip install pandas