# @package _global_
# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override /hydra/hydra_logging: colorlog
  - override /hydra/job_logging: colorlog

# exp_name: ovrd_${hydra:job.override_dirname}
exp_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}

hydra:
  run:
    dir: ${paths.log_dir}/${task_name}/runs/${exp_name}
  sweep:
    dir: ${paths.log_dir}/${task_name}/multiruns/${exp_name}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        exclude_keys:
          - trainer
          - trainer.devices
          - trainer.num_nodes
          - callbacks
          - debug
